### ISSUE TITLE
Option to omit original text when using chat integration

### ISSUE THREAD

**Issue by gsapi** [kelvin124124/ChatTranslated#35]
Hi! Thank you for developing this plugin. I've noticed that when using chat integration, the original message is displayed before the translated message, like in the screenshot below.

![image](https://github.com/user-attachments/assets/28c73989-7db7-4a83-81e2-180d48522539)

This seems a bit redundant to me since the original message is already right above the plugin's message. For long messages, this can clutter the chat box quite a bit. Would it be possible to have a toggle to only show the translated message?

Thanks!

**Comment by kelvin124124** [comment]
So you mean instead of having `(original message) || (translated message)`, we do `(translated message)` only?

Since translation takes time (up to 5 seconds, especially when the first attempt fails), new incoming messages that come in during this time window will cause confusion.

Do you still think it is a good idea to have the option despite it may cause confusion?

**Comment by gsapi** [comment]
I do see the possibility for some confusion if there are many messages being translated, but in my experience translations are near instant (although I am using a DeepL API key)

I still think the option would be good to have to make the chatbox cleaner, the only time I think it may be unsuitable is if multiple people are talking over each other.

**Comment by kelvin124124** [comment]
will add it on next update
